### ISSUE TITLE
Crashes trying to download from lemmy.world

### ISSUE THREAD

**Issue by freekngdom** [CMahaff/lasim#20]
**Describe the Bug**
After entering login details, app crashes trying to load user. Unexpected Error Occurred: "called `Option::unwrap()` on a `None` value"

**Information**
LASIM Version: 0.1.2 lasim_ubuntu.zip
LASIM Profile Version:
Lemmy Source Instance URL: https://lemmy.world
Lemmy Source Instance Version:
Lemmy Target Instance URL:
Lemmy Target Instance Version:

**Output of LASIM**
Unexpected Error Occurred: "called `Option::unwrap()` on a `None` value"

**Comment by freekngdom** [comment]
just tried again and getting same error. Looking through my subs, I'm wondering if it has anything to do with subscriptions that are pending?

**Comment by CMahaff** [comment]
Yeah so full context: I got another report of this same error at a time I know lemmy.world was up, and knowing that I can download my own profile from lemmy.world no issues. Interestingly that user also has quite a large profile :)

So I'm thinking now that it's choking on something specific about certain profiles. I have one user to who sent me their raw profile using the debugging version I have here: https://github.com/CMahaff/lasim/actions/runs/5828356254?pr=34

That version writes out a "raw_profile.json" on download that's basically the raw content from lemmy.world.

If you are comfortable with running that and giving me the raw profile I can use the data to figure out the crash. You'll have to IM it to me somehow though (i.e. @CMahaff@lemmy.world) because it contains personal information like your email, subscription lists, and block lists. I suspect the two of you are having the same issue. No worries if you aren't comfortable doing that - I have at least one problematic profile, but the more the better on the off chance these issues aren't specific.

I have a task to make the "raw profile" dumping an option one can turn on in the future to fight exactly these kind of issues.

I am hoping to look at this issue either tonight or this weekend.

**Comment by CMahaff** [comment]
So the issue I saw from the other user were any subscriptions or blocks to "chirp.social" communities.
