### ISSUE TITLE
Runtime libs in ChromeOS Linux terminal (Debian 11.7)

### ISSUE THREAD

**Issue by jgeorgeson** [CMahaff/lasim#22]
**Describe the Bug**
Trying to run the Ubuntu release in the Linux terminal in ChromeOS. The binary fails to load due to "missing" libssl.so.3. This is the first time I've tried to run LASIM, so there is no prior saved state or profile or anything.

**Information**
LASIM Version: v0.2.0
LASIM Profile Version: Have never run it before, no local state
Lemmy Source Instance URL: N/A
Lemmy Source Instance Version: N/A
Lemmy Target Instance URL: N/A
Lemmy Target Instance Version: N/A

**Output of LASIM**
```shell
$ ./lasim
./lasim: error while loading shared libraries: libssl.so.3: cannot open shared object file: No such file or directory
$ find /lib* /usr/lib* -name libssl*
/usr/lib/x86_64-linux-gnu/libssl3.so
/usr/lib/x86_64-linux-gnu/libssl.so.1.1
$ ldd lasim
./lasim: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by ./lasim)
./lasim: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by ./lasim)
./lasim: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by ./lasim)
        linux-vdso.so.1 (0x00007ffeb5bfb000)
        libssl.so.3 => not found
        libcrypto.so.3 => not found
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007df06cac5000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007df06c981000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007df06c7ad000)
        /lib64/ld-linux-x86-64.so.2 (0x00007df06d56f000)
$ cat /etc/debian_version 
11.7
```

**Comment by CMahaff** [comment]
Well I've certainly never tried it on Chrome OS!

I did some digging and it looks like you need a newer version of openssl, specifically openssl 3.0. This is available in Debian 12, but not Debian 11. The openssl version currently on Debian 11 is also going out of support in September. Some of the other errors about GLIBC may be problematic as well, but I can't know for sure. Overall, I think it'd be much more likely to succeed in Debian 12.

I did manage to build it from source on Debian 11, I had to:
- Install `curl`
- Use the instructions here: https://www.rust-lang.org/tools/install (aka `curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh`)
- Install `build-essential`
- Install `libssl-dev`
- Install `git`
- Clone LASIM source code: `git clone https://github.com/CMahaff/lasim`
- Build LASIM: `cargo build --release` (from within the LASIM folder)
- Executable is in: target/release/lasim
- Execute `cargo clean` to remove artifacts (cleans up about 5GB created during compilation)

I don't see any way to easily automatically build this artifact on Github, and I suspect this issue is limited to older distributions, so I'm not planning to add this artifact in an official capacity unless I find out this is affecting large numbers of Linux users.

If you want my copy of the artifact let me know - unfortunately Github doesn't have any mechanism of me uploading a file in a comment.

**Comment by jgeorgeson** [comment]
Thanks for the write up! I'm looking at a couple of sources on how to upgrade the Linux container.

https://chromeunboxed.com/how-to-switch-your-chromeos-linux-from-debian-to-ubuntu/
https://www.reddit.com/r/chromeos/comments/146cyqi/bookworm_instead_of_bullseye_crostini/

So hopefully with those options I can use the prebuilt binary. Will post back in a few days,

**Comment by jgeorgeson** [comment]
Using this snippet from the reddit link, eventually worked

```bash
sudo -s
apt update
apt upgrade -y
apt autoremove
edit /etc/apt/... and replace bullseye by bookworm
apt update
apt upgrade --without-new-pkgs -y
apt full-upgrade -y
poweroff
```

At first after doing all this all my Linux GUI apps were not launching, but then I got an OS update this morning and now all the apps I had before the upgrade to bookworm and LASIM are all working.

**Comment by CMahaff** [comment]
Fantastic! Glad you got it working!
