### ISSUE TITLE
LASIM fails to open

### ISSUE THREAD

**Issue by CaldeiraG** [CMahaff/lasim#37]
**Describe the Bug**

LASIM fails to open with the following error log, running on Windows:

```
Unexpected Error Occurred: panicked at 'called glCreateShader but it was not loaded.', C:\Users\runneradmin\.cargo\registry\src\index.crates.io-6f17d22bba15001f\glow-0.12.3\src\gl46.rs:4571:5
```

Also cloned the repo, installed Rust and tried to run it to no avail, not familiar with Rust to have a closer look.

**Information**
LASIM Version: 0.2.2
LASIM Profile Version: N/A
Lemmy Source Instance URL: N/A
Lemmy Source Instance Version: N/A
Lemmy Target Instance URL: N/A
Lemmy Target Instance Version: N/A

**Comment by CMahaff** [comment]
Looks like this is an underlying bug with the UI library used by LASIM: https://github.com/slint-ui/slint/issues/2903

Per that issue, looks like running inside a VM without GPU acceleration is the cause of this.

Looks like they have a workaround posted if you want to try that. Alternatively if you also have a Linux VM those should work - I develop LASIM in one :)

I've so far avoided updating LASIM to the latest version of that library because it drastically changes the appearance/size of the UI and seemed to break a lot of the existing code.

**Comment by CMahaff** [comment]
Oh and as far as building it yourself, I'm overdue to write that into the README, but it'd be something like:
1. Install Rust/Cargo: https://www.rust-lang.org/tools/install
2. Potentially some extra steps to get SSL support under Windows?
3. cargo build --release (executable is put into: target/release/lasim)
4. cargo clean (free up the space used by building - which is a lot, several GBs)

**Comment by CaldeiraG** [comment]
Ah interesting, I do have the iGPU passthrough on the VM but it must be using the virtual driver then. 

Also many thanks for the building steps, I'll definitely have a look later when I can.
